name: Feature request
description: Suggest an idea for this project
title: "[Feature] Short Description"
labels: enhancement
body:
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots and Additional Info
    description: |
      Provide any relevant additional information such as screenshots, log files, or other details here.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Checklist
    description: Before submitting your feature request.
    options:
    - label: I have searched the issues and this feature has not been requested.
      required: true
    - label: I am using the most recent skin version.
      required: true