name: Feature request
description: Suggest an idea for this project
title: "[Feature] Short Description"
labels: enhancement
body:
- type: dropdown
  id: skinsection
  attributes:
    label: Skin section
    description: Please select the skin section for the feature
    options:
    - Home Widgets
    - Library Views
    - Fullscreen Video OSD
    - Music Visualisation OSD
    - Video Info Dialog
    - Music Info Dialog
    - PVR and Live TV
    - Mouse and Touch
    - Fonts and Languages
    - Clock and Notifications
    - Other
  validations:
    required: true
- type: textarea
  attributes:
    label: Feature description
    description: A clear and concise description of what you want to happen. Do NOT combine multiple feature requests into one issue. Open new issues for EACH request.
  validations:
    required: true
- type: textarea
  attributes:
    label: Why is this feature needed? Please justify and explain.
    description: A clear and concise explanation justifying why this feature is needed. Ex. I'm always frustrated when [...]
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots and Additional Info
    description: |
      Provide any relevant additional information such as screenshots, log files, or other details here.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Checklist
    description: Before submitting your feature request.
    options:
    - label: I have made a separate issue for each feature I am requesting.
      required: true
    - label: I have searched the issues and this feature has not been requested.
      required: true
    - label: I am using the most recent skin version.
      required: true
